variables:
  GIT_STRATEGY: fetch
  DOCKER_DRIVER: overlay

services:
  - docker:dind

backup:
  image: docker
  stage: build
  retry: 2
  script: |
    # Fetch your CloudFlare API token from here:
    # https://dash.cloudflare.com/profile/api-tokens
    # -> Create Token
    # -> Edit zone DNS
    # -> Permission: read
    # -> Zone resources: Include -> All zones

    docker run -t --rm \
    -e CF_API_TOKEN="$CF_API_TOKEN" \
    lfaoro/flares --all > dns_backup.bind
  artifacts:
    untracked: true
    # uncomment if needed (default is forever on gitlab.com)
    # expire_in: 4 week
    name: "bck-${date}"
    paths:
      - dns_backup.bind
